#!/bin/sh
set -x
git submodule update --init --recursive --depth 1
stow \
    alacritty \
    bash \
    neovim \
    readline \
    tmux \
    vim \
;
nvim +PlugInstall +qall
nvim +'CocInstall -sync coc-clangd' +qall
nvim +'CocInstall -sync coc-python' +qall
